language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t pedropilla/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pedropilla/docker-react npm run test